### PR TITLE
PLAT-229: check code coverage using GitHub Actions

### PR DESCRIPTION
**Pull request by afiskon**
Check code coverage using GitHub Actions.

### CODE REVIEW

**Comment by afiskon** [comment]
Seems to work. All checks were passed, coverage.html was attached in Artifacts.

**Comment by sexyhamster** [comment]
hmmm how to see the report? :octocat:

**Comment by afiskon** [comment]
@sexyhamster  Open Checks tab, find Artifacts on the left, download the archive.

**Comment by sexyhamster** [comment]
that is really hard to control on review >_<

**Comment by afiskon** [comment]
@sexyhamster there is no need to control it during the code review. Total coverage is checked automatically. Currently it's 39.1%, if it drops below 39% the check will not pass.

**Comment by sexyhamster** [comment]
maybe we can do something like https://github.com/jandelgado/golang-ci-template-github-actions ? so it not only check but actually comment

**Comment by afiskon** [comment]
@sexyhamster Coversall looks nice, however I thought the whole idea was not to depend on extra 3rd party service since we had a problem with such services before.

**Comment by sexyhamster** [comment]
hmm, I had no problem with service itself, I was concerned, that it showed random numbers on PR :( Maybe we were doing something wrong. But I really like visual comment, that can control not only threshold for coverage, but coverage changes with each PR. 

Coverage will be run manually in check, but service can actually create comment with diff from master. We could do it without service, I think.

What i want - is to have comment - merging this PR will increase/decrease coverage by N%.

**Comment by afiskon** [comment]
Ok after discussion with @ita-sammann turned out this is not exactly what we wanted. I will consider options with https://coveralls.io/ and https://codecov.io/

**Pull request closed without merging**
